[package]
name = "constructor-asset-extractor"
version = "0.1.0"
authors = ["g <a@b.com>"]

[dependencies]
clap = "~2.27.0"
nom = "^3.2"
byteorder = "1.2.1"
buffer = "0.1.8"
image = "0.18.0"
quick-error = "1.2.1"
maplit = "1.0.1"
